#!/bin/sh

key="/root/.ssh/rocinante@$(hostname -s)"

do_clean() {
  rm -f "${key}" "${key}.pub" "${key}.pw"
}

do_create() {
  do_clean
  mkdir -p -m 0700 /root/.ssh
  touch "${key}.pw"
  chmod 0600 "${key}.pw"
  openssl rand -base64 20 > "${key}.pw"
  openssl genrsa -out "${key}" -passout "file:${key}.pw" 4096
  sshpass -f "${key}.pw" ssh-keygen -y -f "${key}" > "${key}.pub"
  grep -q '^github.com ' .ssh/known_hosts >/dev/null 2>&1 || {
    cat >> /root/.ssh/known_hosts <<'EOF'
github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjM
EOF
  }
  printf '%s\n' "${key}.pub"
}

do_init() {
  test -f "${key}.pub" && printf '%s\n' "${key}.pub" || do_create
}

case "$1" in
  clean|create|init)
    "do_$@"
    exit 0
    ;;

  *)
    echo "unrecognized command: $1"
    exit 100
    ;;
esac

